// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfNS35dG3bjCR4b_Astw3zEM73YQK0kG8',
    appId: '1:330793674299:web:34ee98e4c80bc129321e1e',
    messagingSenderId: '330793674299',
    projectId: 'orienta-urgencias-51d82',
    authDomain: 'orienta-urgencias-51d82.firebaseapp.com',
    storageBucket: 'orienta-urgencias-51d82.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfNS35dG3bjCR4b_Astw3zEM73YQK0kG8',
    appId: '1:330793674299:android:34ee98e4c80bc129321e1e',
    messagingSenderId: '330793674299',
    projectId: 'orienta-urgencias-51d82',
    storageBucket: 'orienta-urgencias-51d82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfNS35dG3bjCR4b_Astw3zEM73YQK0kG8',
    appId: '1:330793674299:ios:34ee98e4c80bc129321e1e',
    messagingSenderId: '330793674299',
    projectId: 'orienta-urgencias-51d82',
    storageBucket: 'orienta-urgencias-51d82.appspot.com',
    iosBundleId: 'com.example.orientaurgencias',
  );

  static const FirebaseOptions macos = ios;

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfNS35dG3bjCR4b_Astw3zEM73YQK0kG8',
    appId: '1:330793674299:web:34ee98e4c80bc129321e1e',
    messagingSenderId: '330793674299',
    projectId: 'orienta-urgencias-51d82',
    authDomain: 'orienta-urgencias-51d82.firebaseapp.com',
    storageBucket: 'orienta-urgencias-51d82.appspot.com',
  );
}
